/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDownloadBar: typeof import('./components/AppDownloadBar.vue')['default']
    BrandLogo: typeof import('./components/BrandLogo.vue')['default']
    HaoluRoadmap: typeof import('./components/lottery/HaoluRoadmap.vue')['default']
    HomeSectionSkeleton: typeof import('./components/home/HomeSectionSkeleton.vue')['default']
    LangPopup: typeof import('./components/LangPopup.vue')['default']
    LangSwitcher: typeof import('./components/LangSwitcher.vue')['default']
    LongDragonPanel: typeof import('./components/lottery/LongDragonPanel.vue')['default']
    LotteryBetBasket: typeof import('./components/lottery/LotteryBetBasket.vue')['default']
    NextResultPopup: typeof import('./components/lottery/NextResultPopup.vue')['default']
    PasswordMismatchHint: typeof import('./components/PasswordMismatchHint.vue')['default']
    RecommendHaoluPanel: typeof import('./components/lottery/RecommendHaoluPanel.vue')['default']
    RecoSimpleBetPopup: typeof import('./components/lottery/RecoSimpleBetPopup.vue')['default']
    Roadmap: typeof import('./components/lottery/Roadmap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonBlock: typeof import('./components/SkeletonBlock.vue')['default']
    TabBar: typeof import('./components/TabBar.vue')['default']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
    TopToast: typeof import('./components/TopToast.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
